import type { Task } from "@/lib/store/types";

// A mix of template-instantiated tasks (from earlier stage moves) and ad-hoc
// tasks assigned directly.
export const tasks: Task[] = [
  // Template tasks from when the SD bid entered Estimating
  {
    id: "task-sd-scope",
    title: "Scope-sheet review & red-tag exclusions",
    assigneeId: "p-angel",
    createdById: "p-casey",
    createdAt: "2026-06-12T16:30:00.000Z",
    dueDate: "2026-06-15T17:00:00.000Z",
    status: "done",
    priority: "high",
    linkedBidId: "bid-sd-cmu",
    stage: "estimating",
    source: "template",
    templateId: "tpl-est-scope",
  },
  {
    id: "task-sd-takeoff",
    title: "Complete takeoff in Bluebeam",
    assigneeId: "p-angel",
    createdById: "p-casey",
    createdAt: "2026-06-12T16:30:00.000Z",
    dueDate: "2026-06-17T17:00:00.000Z",
    status: "done",
    priority: "high",
    linkedBidId: "bid-sd-cmu",
    stage: "estimating",
    source: "template",
    templateId: "tpl-est-takeoff",
  },
  {
    id: "task-sd-capacity",
    title: "Check crew capacity / schedule window with Ops",
    assigneeId: "p-patrick",
    createdById: "p-casey",
    createdAt: "2026-06-12T16:30:00.000Z",
    dueDate: "2026-06-14T17:00:00.000Z",
    status: "inProgress",
    priority: "medium",
    linkedBidId: "bid-sd-cmu",
    stage: "estimating",
    source: "template",
    templateId: "tpl-est-capacity",
    comments: [
      {
        id: "tc-cap-1",
        authorId: "p-angel",
        body: "Schedule window looks tight if we win — what does the August crew picture look like?",
        createdAt: "2026-06-13T15:10:00.000Z",
      },
      {
        id: "tc-cap-2",
        authorId: "p-patrick",
        body: "We'd be pulling a crew off Ontario. Doable, but only if mobilization holds to the 18th. If it slips a week we're double-booked.",
        createdAt: "2026-06-13T18:42:00.000Z",
      },
    ],
  },

  // Template tasks from Lincoln paver entering Handoff
  {
    id: "task-lp-foreman",
    title: "Assign & brief foreman (2 weeks out)",
    description: "Resolve the saw/tooling question with Jeff before mobilization.",
    assigneeId: "p-patrick",
    createdById: "p-tucker",
    createdAt: "2026-06-15T16:30:00.000Z",
    dueDate: "2026-06-22T17:00:00.000Z",
    status: "blocked",
    priority: "high",
    linkedBidId: "bid-lincoln-paver",
    stage: "handoff",
    source: "template",
    templateId: "tpl-ho-foreman",
    comments: [
      {
        id: "tc-fore-1",
        authorId: "p-patrick",
        body: "Holding on this — Jeff still hasn't confirmed whether we own the saw or the GC supplies it. Can't brief a foreman without it.",
        createdAt: "2026-06-16T14:05:00.000Z",
      },
      {
        id: "tc-fore-2",
        authorId: "p-tucker",
        body: "Chasing Jeff today. Will move back to In Progress the moment we have an answer.",
        createdAt: "2026-06-16T16:20:00.000Z",
      },
    ],
  },
  {
    id: "task-lp-meeting",
    title: "Run estimating → ops handoff meeting",
    assigneeId: "p-tucker",
    createdById: "p-tucker",
    createdAt: "2026-06-15T16:30:00.000Z",
    dueDate: "2026-06-19T17:00:00.000Z",
    status: "done",
    priority: "high",
    linkedBidId: "bid-lincoln-paver",
    stage: "handoff",
    source: "template",
    templateId: "tpl-ho-meeting",
  },

  // Ad-hoc tasks
  {
    id: "task-adhoc-rebar",
    title: "Get rebar spacing clarification from GC on SD CMU",
    description:
      "No structural details on the set. Confirm spacing & control-joint locations before we lock the number.",
    assigneeId: "p-angel",
    createdById: "p-patrick",
    createdAt: "2026-06-21T17:00:00.000Z",
    dueDate: "2026-06-24T17:00:00.000Z",
    status: "todo",
    priority: "high",
    linkedBidId: "bid-sd-cmu",
    source: "adhoc",
  },
  {
    id: "task-adhoc-ontario-green",
    title: "Re-sequence Ontario crews to recover production",
    description: "Work is too spread out — green days are slipping. Game-plan with Luke.",
    assigneeId: "p-luke",
    createdById: "p-patrick",
    createdAt: "2026-06-20T15:00:00.000Z",
    dueDate: "2026-06-23T17:00:00.000Z",
    status: "inProgress",
    priority: "high",
    linkedBidId: "bid-ontario",
    source: "adhoc",
  },
  {
    id: "task-adhoc-az-wage",
    title: "Build AZ prevailing-wage parameter set",
    description: "Mesa tilt-up needs a clean wage determination before pricing labor.",
    assigneeId: "p-casey",
    createdById: "p-rohilio",
    createdAt: "2026-06-19T16:00:00.000Z",
    dueDate: "2026-07-01T17:00:00.000Z",
    status: "todo",
    priority: "medium",
    linkedBidId: "bid-mesa-tilt",
    source: "adhoc",
  },
  {
    id: "task-adhoc-monday",
    title: "Consolidate Monday.com boards into one project view",
    assigneeId: "p-abby",
    createdById: "p-tucker",
    createdAt: "2026-06-18T16:00:00.000Z",
    dueDate: "2026-06-30T17:00:00.000Z",
    status: "todo",
    priority: "low",
    source: "adhoc",
  },

  // ── Recurring / standing work ──────────────────────────────────────────
  // Completing one of these spawns the next occurrence automatically.
  {
    id: "task-rec-capacity-sync",
    title: "Weekly Ops ↔ Estimating capacity sync",
    description:
      "Walk the active bids vs. crew availability so nothing gets committed we can't man.",
    assigneeId: "p-patrick",
    createdById: "p-casey",
    createdAt: "2026-06-01T15:00:00.000Z",
    dueDate: "2026-06-25T16:00:00.000Z",
    status: "todo",
    priority: "high",
    source: "adhoc",
    recurrence: { cadence: "weekly" },
  },
  {
    id: "task-rec-procurement-review",
    title: "Weekly procurement risk review",
    description: "Check long-lead items against need-by dates across all projects.",
    assigneeId: "p-abby",
    createdById: "p-patrick",
    createdAt: "2026-06-01T15:00:00.000Z",
    dueDate: "2026-06-26T16:00:00.000Z",
    status: "todo",
    priority: "medium",
    source: "adhoc",
    recurrence: { cadence: "weekly" },
  },
  {
    id: "task-rec-pipeline-review",
    title: "Weekly bid pipeline review",
    assigneeId: "p-casey",
    createdById: "p-casey",
    createdAt: "2026-06-01T15:00:00.000Z",
    dueDate: "2026-06-24T15:00:00.000Z",
    status: "inProgress",
    priority: "medium",
    source: "adhoc",
    recurrence: { cadence: "weekly" },
  },
  {
    id: "task-rec-wage-refresh",
    title: "Monthly AZ/NV prevailing-wage refresh",
    description: "Pull the latest wage determinations before they go stale on open bids.",
    assigneeId: "p-rohilio",
    createdById: "p-casey",
    createdAt: "2026-06-01T15:00:00.000Z",
    dueDate: "2026-07-01T16:00:00.000Z",
    status: "todo",
    priority: "low",
    source: "adhoc",
    recurrence: { cadence: "monthly" },
  },
];
